# -*- coding: utf-8 -*-
"""chess game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zsx2QCw-e_SwSd-TVcYDfM0F4oQzFFxW
"""

pip install python-chess

import chess
import chess.engine

def print_board(board):
    print(board)

def get_move():
    return input("Enter your move (e.g., e2e4): ")

def main():
    board = chess.Board()

    print("Welcome to Chess!")
    print("Enter moves in UCI format (e.g., 'e2e4') or type 'quit' to exit.")
    print_board(board)

    while not board.is_game_over():
        # Player's move
        player_move = get_move()
        if player_move.lower() == 'quit':
            break

        try:
            move = chess.Move.from_uci(player_move)
            if move in board.legal_moves:
                board.push(move)
                print_board(board)
            else:
                print("Invalid move. Try again.")
                continue
        except ValueError:
            print("Invalid format. Please use UCI format (e.g., 'e2e4').")
            continue

        # Check if game is over
        if board.is_checkmate():
            print("Checkmate!")
            break
        elif board.is_stalemate():
            print("Stalemate!")
            break
        elif board.is_insufficient_material():
            print("Draw due to insufficient material!")
            break
        elif board.is_seventyfive_moves():
            print("Draw due to 75-move rule!")
            break
        elif board.is_fivefold_repetition():
            print("Draw due to fivefold repetition!")
            break
        elif board.is_variant_draw():
            print("Draw by variant!")
            break

    print("Game over.")
    print("Final position:")
    print_board(board)

if __name__ == "__main__":
    main()